"""query_logs: add model_requested and commit_sha

Revision ID: 7e49eeb7f12a
Revises: 27d1a3b129f9
Create Date: 2026-09-21 17:31:19.863494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e49eeb7f12a'
down_revision: Union[str, Sequence[str], None] = '27d1a3b129f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('model_requested', sa.String(length=64), nullable=True))
    op.add_column('query_logs', sa.Column('commit_sha', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'commit_sha')
    op.drop_column('query_logs', 'model_requested')
    # ### end Alembic commands ###
